### ISSUE TITLE
Couple of comments on creating operator using an existing Helm chart

### ISSUE THREAD

**Issue by spzala** [IBM/operator-guild#5]
The existing_helm_chart_operator.md works great, but couple of observations/nits? 
1) 
In order to keep the flow intact, may want to make small changes below: 
a Kustomization.yaml for customizing manifests  - this file is not in the root dir like other files. May be better to say - “ a config directory containing kustomization.yaml"> ? 
Same for the Patch files. 
2)
export USERNAME=`<docker-registry>` - something like `<docker-registry-userID>`  (instead of `<docker-registry>`) ? 
3)
"Let's stops your WordPress web server wordpress-demo" - good idea to point to how to stop (something like Let's stop running following command...) Also `stop` instead of `stops`.

**Comment by hickeyma** [comment]
Thanks for the review comments @spzala.

> In order to keep the flow intact, may want to make small changes below:
a Kustomization.yaml for customizing manifests - this file is not in the root dir like other files. May be better to say - “ a config directory containing kustomization.yaml"> ?
Same for the Patch files.

That's a good point. However, as it is just a listing off of what is provided from the scaffold and it is not an actual file list then I am going to leave it as is.

> export USERNAME=<docker-registry> - something like <docker-registry-userID> (instead of <docker-registry>) ?

Done

> "Let's stops your WordPress web server wordpress-demo" - good idea to point to how to stop (something like Let's stop running following command...) Also stop instead of stops.

The steps are part of the bullet points underneath. Maybe take a look again and see if you can find way to better improve it?

FYI, PR #6 has updates and some more imrpovements.

**Comment by spzala** [comment]
> Thanks for the review comments @spzala.
> 
> > In order to keep the flow intact, may want to make small changes below:
> > a Kustomization.yaml for customizing manifests - this file is not in the root dir like other files. May be better to say - “ a config directory containing kustomization.yaml"> ?
> > Same for the Patch files.
> 
> That's a good point. However, as it is just a listing off of what is provided from the scaffold and it is not an actual file list then I am going to leave it as is.
> 
> > export USERNAME= - something like  (instead of ) ?
> 
> Done
> 
> > "Let's stops your WordPress web server wordpress-demo" - good idea to point to how to stop (something like Let's stop running following command...) Also stop instead of stops.
> 
> The steps are part of the bullet points underneath. Maybe take a look again and see if you can find way to better improve it?
> 
> FYI, PR #6 has updates and some more imrpovements.

Awesome, thanks for the PR @hickeyma I have couple of questions but will ping for a quick discussion.
